export const API = {
  PROJECT: {
    LIST: "/tours",
    DETAIL: (id) => `/tours/${id}`,
    CREATE: "/tours",
    EDIT: (id) => `/tours/${id}`,
    DELETE: (id) => `/tours/${id}`,
    LIST_LOCATION: `/list-location`,
  },
  PRESS: {
    LIST: "/custom-tours",
    DETAIL: (id) => `/custom-tours/${id}`,
    CREATE: "/custom-tours",
    EDIT: (id) => `/custom-tours/${id}`,
    DELETE: (id) => `/custom-tours/${id}`,
    LIST_LOCATION: `/list-custom-location`,
  },
  SPIN: {
    LIST: "/spin-sessions",
    DETAIL: (id) => `/video/${id}`,
    CREATE: "/video",
    EDIT: (id) => `/video/${id}`,
    DELETE: (id) => `/video/${id}`,
  },
  MONEY: {
    SESSION: "/deposit/create",
    DETAIL_SESSION: (id) => `/deposit/${id}`,
    HISTORY_OUT: "/deposit/history-out",
    HISTORY_OUT_ADMIN: "/deposit/history-out-admin",
    HISTORY_IN: `/deposit/history-in`,
    REQUEST_OUT: `/wallet/request-out`,
    DETAIL_BALANCE: "/wallet/balance",
    USER_BANK: "/users/bank",
    USER_ME_BANK: "/users/me-bank",
    BANK_ADMIN: (id) => `/users/admin-user-bank/${id}`,
    CONFIRM_OUT: "/wallet/confirm-request-out",
    HISTORY_JOINED: `/deposit/history-joined`,
    HISTORY_WIN: `/deposit/history-win`,
  },
  CLIENT: {
    LIST: "/client",
    DETAIL: (id) => `/client/${id}`,
    CREATE: "/client",
    EDIT: (id) => `/client/${id}`,
    DELETE: (id) => `/client/${id}`,
  },
  USER: {
    DETAIL: (id) => `/users/profile/${id}`,
    SIGNIN_GG: "/auth/social-login",
    UPDATE: "/change-password",
    UPDATE_AVATAR: "/upload",
    REGISTER: "/auth/register",
    SIGNIN_ACCOUNT: "/auth/login",
    UPDATE_PASS: "/auth/forgot-password",
  },
};

export const QUERY_KEY = {
  JOB: {
    LIST: "get-list-job",
    DETAIL: "get-job-detail",
    CREATE: "create-job",
    EDIT: "edit-job",
    DELETE: "delete-job",
    RECEIVE: "receive-job",
    JOB_CREATED: "job-created",
    JOB_BIDED: "job-bided",
    JOB_RECEIVED: "job-received",
    RECEIVE_BID: "receive-bid",
    DETAIL_BID_JOB: "detail-bid-job",
  },
  USER: {
    DETAIL: "get-user-detail",
    SIGNIN: "signin-user",
    UPDATE: "update-user",
  },
};
